export const WANA = {
  nav: {
    home: 'nav-home',
    monitor: 'nav-monitor',
    brief: 'nav-brief',
    alerts: 'nav-alerts',
    spatial: 'nav-spatial',
    evidence: 'nav-evidence',
    theory: 'nav-theory',
    about: 'nav-about',
    contact: 'nav-contact',
    mobileMenu: 'nav-mobile-menu-toggle',
    languageToggle: 'language-toggle',
    languageOptionId: 'language-option-id',
    languageOptionEn: 'language-option-en',
  },
  landing: {
    heroCta: 'landing-hero-cta-monitor',
    heroCtaBrief: 'landing-hero-cta-brief',
    heroCtaAlerts: 'landing-hero-cta-alerts',
  },
  monitor: {
    searchInput: 'monitor-search-input',
    regionSelect: 'monitor-region-select',
    statusSelect: 'monitor-status-select',
    refreshBtn: 'monitor-refresh-btn',
    table: 'monitor-table',
    row: (id) => `monitor-row-${id}`,
    viewBtn: (id) => `monitor-view-${id}`,
  },
  brief: {
    titleInput: 'brief-title-input',
    languageSelect: 'brief-language-select',
    textArea: 'brief-text-area',
    fileInput: 'brief-file-input',
    generateBtn: 'brief-generate-btn',
    pasteSampleBtn: 'brief-paste-sample-btn',
    pdfBtn: 'brief-export-pdf-btn',
    resultCard: 'brief-result-card',
  },
  alerts: {
    list: 'alerts-list',
    item: (id) => `alert-item-${id}`,
    markRead: (id) => `alert-mark-read-${id}`,
    regionFilter: 'alerts-region-filter',
    priorityFilter: 'alerts-priority-filter',
    subscribeBtn: 'alerts-subscribe-btn',
    subscribeNameInput: 'alerts-subscribe-name',
    subscribeOrgInput: 'alerts-subscribe-org',
    subscribeContactInput: 'alerts-subscribe-contact',
    subscribeRegionSelect: 'alerts-subscribe-region',
    subscribeChannelSelect: 'alerts-subscribe-channel',
    subscribeSubmit: 'alerts-subscribe-submit',
  },
  spatial: {
    map: 'spatial-map',
    territoryItem: (id) => `spatial-territory-${id}`,
    legendOverlap: 'spatial-legend-overlap',
  },
  evidence: {
    newCaseBtn: 'evidence-new-case-btn',
    caseNameInput: 'evidence-case-name',
    communityInput: 'evidence-community',
    regionInput: 'evidence-region',
    submitBtn: 'evidence-submit',
    packItem: (id) => `evidence-pack-${id}`,
    checklistItem: (key) => `evidence-checklist-${key}`,
    objectionTextarea: 'evidence-objection-textarea',
    saveBtn: 'evidence-save-btn',
    statusSelect: 'evidence-status-select',
    uploadZone: 'evidence-upload-zone',
    uploadInput: 'evidence-upload-input',
    uploadCategory: 'evidence-upload-category',
    fileCard: (id) => `evidence-file-${id}`,
    fileOpenBtn: (id) => `evidence-file-open-${id}`,
    fileDeleteBtn: (id) => `evidence-file-delete-${id}`,
    fileVerifyBtn: (id) => `evidence-file-verify-${id}`,
    deleteConfirmYes: 'evidence-delete-confirm-yes',
    readinessBar: 'evidence-readiness-bar',
  },
  contact: {
    nameInput: 'contact-name-input',
    emailInput: 'contact-email-input',
    orgInput: 'contact-org-input',
    messageInput: 'contact-message-input',
    submitBtn: 'contact-submit-btn',
  },
};
